var contas = {
    "usuarios": [
        {
            "nome": "Filipe",
            "sobrenome": "Iannarelli Caldeira",
            "email": "lipe.iannarelli@gmail.com",
            "nickname": "filipe",
            "senha": "12345",
            "transacoes": [
                {
                    "id": 1,
                    "vencimento": {
                        "data": "2018-11-25",
                        "dia": 25,
                        "mes": 11,
                        "ano": 2018,
                    },
                    "historico": "Saldo Inicial",
                    "complemento": "",
                    "realizado": "",
                    "entrada": "",
                    "saida": "",
                    "saldo": "3875.49",
                },
                {
                    "id": 2,
                    "vencimento": {
                        "data": "2018-11-26",
                        "dia": 26,
                        "mes": 11,
                        "ano": 2018,
                    },
                    "historico": "Escola das crianças",
                    "complemento": "Escola Abecedário",
                    "realizado": "2018-11-26",
                    "entrada": "",
                    "saida": "2150.00",
                    "saldo": "",
                },
                {
                    "id": 3,
                    "vencimento": {
                        "data": "2018-12-05",
                        "dia": 5,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Conta de luz",
                    "complemento": "CEMIG",
                    "realizado": "2018-12-05",
                    "entrada": "",
                    "saida": "121.90",
                    "saldo": "",
                },
                {
                    "id": 4,
                    "vencimento": {
                        "data": "2018-12-05",
                        "dia": 5,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Salário",
                    "complemento": "Empresa XYZ",
                    "realizado": "2018-12-05",
                    "entrada": "4500.00",
                    "saida": "",
                    "saldo": "",
                },
                {
                    "id": 5,
                    "vencimento": {
                        "data": "2018-12-10",
                        "dia": 10,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Aluguel",
                    "complemento": "",
                    "realizado": "",
                    "entrada": "",
                    "saida": "980.00",
                    "saldo": "",
                },
                {
                    "id": 6,
                    "vencimento": {
                        "data": "2018-12-15",
                        "dia": 15,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Cartão de Crédito",
                    "complemento": "Banco ABC",
                    "realizado": "",
                    "entrada": "",
                    "saida": "3046.54",
                    "saldo": "",
                },
                {
                    "id": 7,
                    "vencimento": {
                        "data": "2018-12-15",
                        "dia": 15,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Condomínio",
                    "complemento": "",
                    "realizado": "",
                    "entrada": "",
                    "saida": "150.00",
                    "saldo": "",
                },
                {
                    "id": 8,
                    "vencimento": {
                        "data": "2018-12-20",
                        "dia": 20,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Parcela 8/10 - Empréstimo",
                    "complemento": "Recebimento - vizinho",
                    "realizado": "",
                    "entrada": "200.00",
                    "saida": "",
                    "saldo": "",
                },
                {
                    "id": 9,
                    "vencimento": {
                        "data": "2018-12-20",
                        "dia": 20,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Parcela 30/60",
                    "complemento": "Financiamento carro",
                    "realizado": "",
                    "entrada": "",
                    "saida": "430.00",
                    "saldo": "",
                },
                {
                    "id": 10,
                    "vencimento": {
                        "data": "2018-12-20",
                        "dia": 20,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Salário - Adiantamento",
                    "complemento": "Empresa XYZ",
                    "realizado": "",
                    "entrada": "1500.00",
                    "saida": "",
                    "saldo": "",
                },
                {
                    "id": 11,
                    "vencimento": {
                        "data": "2018-12-26",
                        "dia": 26,
                        "mes": 12,
                        "ano": 2018,
                    },
                    "historico": "Escola das crianças",
                    "complemento": "Escola Abecedário",
                    "realizado": "",
                    "entrada": "",
                    "saida": "2150.00",
                    "saldo": "",
                },
                {
                    "id": 12,
                    "vencimento": {
                        "data": "2019-01-05",
                        "dia": 5,
                        "mes": 1,
                        "ano": 2019,
                    },
                    "historico": "Conta de luz",
                    "complemento": "CEMIG",
                    "realizado": "",
                    "entrada": "",
                    "saida": "120.10",
                    "saldo": "",
                },
                {
                    "id": 13,
                    "vencimento": {
                        "data": "2019-01-05",
                        "dia": 5,
                        "mes": 1,
                        "ano": 2019,
                    },
                    "historico": "Salário",
                    "complemento": "Empresa XYZ",
                    "realizado": "",
                    "entrada": "4500.00",
                    "saida": "",
                    "saldo": "",
                },
            ],
        },
    ],
}